[project]
name = "check-azure-rbac-permission-mismatch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-identity>=1.21.0",
    "requests>=2.32.3",
]
