[project]
name = "clone-or-pull-repos"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "colorama==0.4.6 ; sys_platform == 'win32'",
    "python-decouple==3.8",
    "send2trash>=1.8.3",
    "tqdm==4.67.1",
]
