[tool.poetry]
name = "book-bot"
version = "0.1.0"
description = ""
authors = ["Matei Pinzaru <matei@avocado.solutions>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
